image: gcc

before_script:
    - apt update && apt -y install make autoconf bsdmainutils valgrind
    - rm -rf /etc/localtime
    - ln -s /usr/share/zoneinfo/Europe/Paris /etc/localtime
    - date

build-cassini:
  stage: build
  script:
    - gcc --version
    - make cassini
  artifacts:
    paths:
      - cassini
  cache:
    paths:
      - "_build/*.o"

test-cassini:
  stage: test
  script:
    - ./run-cassini-tests.sh
