image: gcc

before_script:
    - apt update && apt -y install make autoconf hexdump valgrind

build:
  stage: build
  script:
    - gcc --version
    - make cassini
  artifacts:
    paths:
      - cassini
  cache:
    paths:
      - "_build/*.o"

test:
  stage: test
  script:
    - ./run-cassini-tests.sh
